### ISSUE TITLE
Add docker image cache

### ISSUE THREAD

**Issue by wopox1337** [Re-HLDS/testdemos#23]
- https://github.com/marketplace/actions/cache

**Comment by wopox1337** [comment]
I tried and it didn't work. We need to find a way to cache Docker build without using the `docker-build-push` action.

```yaml
steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.test.type }}
          restore-keys: |
            ${{ runner.os }}-docker-
        
      - name: Prepare
        working-directory: ./testdemos_files
        run: rsync -a deps/${{ matrix.test.type }}/* .

      - name: Build container
        run: |
          docker build \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max \
          -t $imageName .

      - name: Run test
        if: false
        env:
          demo: ${{ matrix.test.file }}
          desc: ${{ matrix.test.desc }}
        run: |
          docker run \
            --env demo \
            --env desc \
            -t $imageName \
            ./runTest.sh

```
